# Config file for automatic testing at travis-ci.org

language: python

python: 
  "2.7"
  "3.5"
  "3.6"

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV -- --keepdb --parallel

after_success:
  - codecov -e TOX_ENV
